const AUTH_ACTION_TYPE_LOG_IN = 'AUTH_ACTION_TYPE_LOG_IN';
const AUTH_ACTION_TYPE_LOG_IN_FACEBOOK = 'AUTH_ACTION_TYPE_LOG_IN_FACEBOOK';
const AUTH_ACTION_TYPE_LOG_OUT = 'AUTH_ACTION_TYPE_LOG_OUT';
const AUTH_ACTION_TYPE_CHANGE_GOOGLE_MAPS_SESSION_TOKEN = 'AUTH_ACTION_TYPE_CHANGE_GOOGLE_MAPS_SESSION_TOKEN';
const AUTH_ACTION_TYPE_CHANGE_REQUEST = "AUTH_ACTION_TYPE_CHANGE_REQUEST";
const AUTH_ACTION_TYPE_CHANGE_USER = "AUTH_ACTION_TYPE_CHANGE_USER";
const AUTH_ACTION_TYPE_CHANGE_PARTIAL_AUTH = "AUTH_ACTION_TYPE_CHANGE_PARTIAL_AUTH";


export {
    AUTH_ACTION_TYPE_LOG_IN,
    AUTH_ACTION_TYPE_LOG_IN_FACEBOOK,
    AUTH_ACTION_TYPE_LOG_OUT,
    AUTH_ACTION_TYPE_CHANGE_GOOGLE_MAPS_SESSION_TOKEN,
    AUTH_ACTION_TYPE_CHANGE_REQUEST,
    AUTH_ACTION_TYPE_CHANGE_USER,
    AUTH_ACTION_TYPE_CHANGE_PARTIAL_AUTH
}