const BOOK_ACTION_TYPE_CHANGE_CLIENT_ID = "BOOK_ACTION_TYPE_CHANGE_CLIENT_ID";
const BOOK_ACTION_TYPE_CHANGE_LOCATION = "BOOK_ACTION_TYPE_CHANGE_LOCATION";
const BOOK_ACTION_TYPE_CHANGE_PRODUCT = "BOOK_ACTION_TYPE_CHANGE_PRODUCT";
const BOOK_ACTION_TYPE_CHANGE_TOTAL = "BOOK_ACTION_TYPE_CHANGE_TOTAL";
const BOOK_ACTION_TYPE_CHANGE_QUANTITY = "BOOK_ACTION_TYPE_CHANGE_QUANTITY";
const BOOK_ACTION_TYPE_CHANGE_ISREQUESTING = "BOOK_ACTION_TYPE_CHANGE_ISREQUESTING";
const BOOK_ACTION_TYPE_CHANGE_STATUS = "BOOK_ACTION_TYPE_CHANGE_STATUS";
const BOOK_ACTION_TYPE_CHANGE_DEVICE_TOKEN = "BOOK_ACTION_TYPE_CHANGE_DEVICE_TOKEN";
const BOOK_ACTION_TYPE_ADD_PRODUCT = "BOOK_ACTION_TYPE_ADD_PRODUCT";
const BOOK_ACTION_TYPE_ADD_PRODUCTS = "BOOK_ACTION_TYPE_ADD_PRODUCTS";
const BOOK_ACTION_TYPE_ADD_SERVICE = "BOOK_ACTION_TYPE_ADD_SERVICE";
const BOOK_ACTION_TYPE_CHANGE_QUANTITY_BY_PRODUCT_ID = "BOOK_ACTION_TYPE_CHANGE_QUANTITY_BY_PRODUCT_ID";

export {
    BOOK_ACTION_TYPE_CHANGE_CLIENT_ID,
    BOOK_ACTION_TYPE_CHANGE_LOCATION,
    BOOK_ACTION_TYPE_CHANGE_PRODUCT,
    BOOK_ACTION_TYPE_CHANGE_TOTAL,
    BOOK_ACTION_TYPE_CHANGE_QUANTITY,
    BOOK_ACTION_TYPE_CHANGE_ISREQUESTING,
    BOOK_ACTION_TYPE_CHANGE_STATUS,
    BOOK_ACTION_TYPE_CHANGE_DEVICE_TOKEN,
    BOOK_ACTION_TYPE_ADD_PRODUCT,
    BOOK_ACTION_TYPE_ADD_PRODUCTS,
    BOOK_ACTION_TYPE_ADD_SERVICE,
    BOOK_ACTION_TYPE_CHANGE_QUANTITY_BY_PRODUCT_ID
}