const BOOKING_ACTION_TYPE_CHANGE_DATA = "BOOKING_ACTION_TYPE_CHANGE_DATA";
const BOOKING_ACTION_TYPE_CHANGE_REQUEST = "BOOKING_ACTION_TYPE_CHANGE_REQUEST";

export {
    BOOKING_ACTION_TYPE_CHANGE_DATA,
    BOOKING_ACTION_TYPE_CHANGE_REQUEST,
}