const BUSINESS_ACTION_CHANGE_BUSINESSES = 'BUSINESS_ACTION_CHANGE_BUSINESSES';
const BUSINESS_ACTION_CHANGE_CURRENT = "BUSINESS_ACTION_CHANGE_CURRENT";
const BUSINESS_ACTION_CHANGE_REQUEST = "BUSINESS_ACTION_CHANGE_REQUEST";

export {
    BUSINESS_ACTION_CHANGE_BUSINESSES,
    BUSINESS_ACTION_CHANGE_CURRENT,
    BUSINESS_ACTION_CHANGE_REQUEST
}