const JOB_ACTIVE_ACTION_TYPE_CHANGE_DATA = "JOB_ACTIVE_ACTION_TYPE_CHANGE_DATA";
const JOB_ACTIVE_ACTION_TYPE_CHANGE_REQUEST = "JOB_ACTIVE_ACTION_TYPE_CHANGE_REQUEST";

export {
    JOB_ACTIVE_ACTION_TYPE_CHANGE_DATA,
    JOB_ACTIVE_ACTION_TYPE_CHANGE_REQUEST,
}