const JOB_ACTION_TYPE_CHANGE_DATA = "JOB_ACTION_TYPE_CHANGE_DATA";
const JOB_ACTION_TYPE_CHANGE_REQUEST = "JOB_ACTION_TYPE_CHANGE_REQUEST";
const JOB_ACTION_TYPE_CHANGE_ACCEPT_REQUEST = "JOB_ACTION_TYPE_CHANGE_ACCEPT_REQUEST";
const JOB_ACTION_TYPE_CHANGE_ACTIVE_DATA = "JOB_ACTION_TYPE_CHANGE_ACTIVE_DATA";

export {
    JOB_ACTION_TYPE_CHANGE_DATA,
    JOB_ACTION_TYPE_CHANGE_REQUEST,
    JOB_ACTION_TYPE_CHANGE_ACCEPT_REQUEST,
    JOB_ACTION_TYPE_CHANGE_ACTIVE_DATA
}