const NOTIFICATION_ACTION_TYPE_CHANGE_DATA = "NOTIFICATION_ACTION_TYPE_CHANGE_DATA"; 
const NOTIFICATION_ACTION_TYPE_CHANGE_REQUEST = "NOTIFICATION_ACTION_TYPE_CHANGE_REQUEST";

export {
    NOTIFICATION_ACTION_TYPE_CHANGE_DATA,
    NOTIFICATION_ACTION_TYPE_CHANGE_REQUEST
}