const PERMISSION_ACTION_TYPE_LOCATION = "PERMISSION_ACTION_TYPE_LOCATION";
const PERMISSION_ACTION_TYPE_LOCATION_STATUS = "PERMISSION_ACTION_TYPE_LOCATION_STATUS";
const PERMISSION_ACTION_TYPE_LOCATION_SCREEN = "PERMISSION_ACTION_TYPE_LOCATION_SCREEN";
const PERMISSION_ACTION_TYPE_LOCATION_ERROR = "PERMISSION_ACTION_TYPE_LOCATION_ERROR";
export {
    PERMISSION_ACTION_TYPE_LOCATION,
    PERMISSION_ACTION_TYPE_LOCATION_STATUS,
    PERMISSION_ACTION_TYPE_LOCATION_SCREEN,
    PERMISSION_ACTION_TYPE_LOCATION_ERROR
}